weights: /home/berkay/Desktop/traffic-sign/yolov5/runs/train/exp16/weights/best.pt
cfg: /home/berkay/Desktop/traffic-sign/yolov5/models/yolov5s.yaml
data: dataset_bolt.yaml
hyp: /home/berkay/Desktop/traffic-sign/yolov5/data/hyps/exp17.yaml
epochs: 75
batch_size: 32
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
optimizer: AdamW
sync_bn: false
workers: 8
project: runs/train
name: exp
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 25
freeze:
- 0
save_period: -1
seed: 0
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs/train/exp17
